class matrix:
    data: list[list[float]]
    rows: int
    cols: int
    def __init__(self, width=0, heigt=0) -> None: ...
    def to_list(self) -> list[list[float]]: ...

def ones(rows: int, cols: int) -> matrix: ...
def zeros(rows: int, cols: int) -> matrix: ...
def random(rows: int, cols: int) -> matrix: ...
def matrix_from(data: list[list[float]]) -> matrix: ...
