import numpy as np

class matrix:
    shape: tuple[int, int]
    ndim: int
    size: int
    device: str
    dtype: np.dtype
    def __init__(self, width=0, heigt=0) -> None: ...
    def to_list(self) -> list[list[float]]: ...
    def numpy(self) -> np.ndarray: ...
    def __array__(self) -> np.ndarray: ...
    def to_numpy(self) -> np.ndarray: ...

def ones(rows: int, cols: int) -> matrix: ...
def zeros(rows: int, cols: int) -> matrix: ...
def random(rows: int, cols: int) -> matrix: ...
def from_list(data: list[list[float]]) -> matrix: ...
def from_numpy(data: np.ndarray) -> matrix: ...